### ISSUE TITLE
Unable to `runnable ssh` for a branch with a `/` in the name

### ISSUE THREAD

**Issue by vinsidious** [Runnable/cli#56]
There's currently a bug affecting users who try to `runnable ssh` for a branch with a forward slash in the name. Our engineers like to prefix their feature branches with their name (i.e. `vince/new-feature`) which means we're forced to type in the full container name when SSH'ing into a container.

I've submitted a PR with a fix [#55]

**Comment by anandkumarpatel** [comment]
Fixed via #55
